export const LOGIN = 'LOGIN';
export const LOGIN_REDUCER = 'LOGIN_REDUCER';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_REDUCER = 'SIGNUP_REDUCER';
export const CREATE_PROPERTY = 'CREATE_PROPERTY';
export const CREATE_PROPERTY_REDUCER = 'CREATE_PROPERTY_REDUCER';
